# Generated by Django 3.2.4 on 2021-07-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=50)),
                ('cinema_address', models.TextField()),
                ('cinema_city', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, unique=True)),
                ('movie_genre', models.CharField(max_length=25)),
                ('movie_cast', models.TextField()),
                ('movie_duration', models.IntegerField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=20)),
                ('person_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_seats', models.IntegerField()),
                ('show_start_time', models.DateTimeField(auto_now_add=True)),
                ('show_end_time', models.DateTimeField(auto_now_add=True)),
                ('total_seats', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApi.cinema')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApi.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApi.personaldetails')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApi.showtime')),
            ],
        ),
    ]
