# Generated by Django 3.2.4 on 2021-07-05 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='person_number',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='person_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
