# Generated by Django 3.2.4 on 2021-07-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApi', '0002_auto_20210705_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='cinema_id',
            new_name='cinema',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
